### ISSUE TITLE
How to use in game?

### ISSUE THREAD

**Issue by Philipou** [Earthcomputer/update-depression#1]
Hey, i did gradlew.bat build and installed the mod in my game but can't find how to use it, no options, keybinds items, or anything... Thanks, -Philipou

**Comment by Earthcomputer** [comment]
You read the code and figure it out

**Comment by Philipou** [comment]
Ok ill try but isnt it like easier if you just explain ? But thanks ill try to read the code

**Comment by Philipou** [comment]
Oh ok i found how to use it with the command /setsuppressedshulkerbox and this code : 
![image](https://github.com/Earthcomputer/update-depression/assets/71514309/dd5d6b20-d584-4745-9c99-c5f3c9059019)

I just want to know is there any additional things to the mod before i close the "issue" ?

**Comment by Earthcomputer** [comment]
Check out `/config` too.
